<?php
/**
 * Generated by framework installer - Thu, 26 Nov 2015 18:40:25 +0000
*/
    class Config
    {
	const BASEDNAME	= '/framework';
	const DBHOST	= 'localhost';
	const DB	= 'openaccess';
	const DBUSER	= 'oa';
	const DBPW	= '23101995';
	const SITENAME	= 'OpenAccessNCL';
	const SITEURL	= 'http://openaccess.org';
	const SITENOREPLY	= 'noreply@openaccess.com';
	const SYSADMIN	= 'danhthanhnguyen1995@gmail.com';
    }
?>
